sudo: required
services:
    - docker

before_install:
    - docker build -t hkalva/docker-react -f Dockerfile.dev .  

script:
    - docker run -e CI=true hkalva/docker-react npm run test

deploy:
    edge: true
    provider: elsaticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    buket_name: "elasticbeanstalk-us-east-1-267479437291"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY